VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.synced_folder "./config", "/vagrant", type: "virtualbox"
    #First machine (server)
    config.vm.define "jerdos-sS" do |server|
        server.vm.box = "ubuntu/bionic64"
        server.vm.hostname = "jerdos-sS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "virtualbox" do |vb|
            vb.name = "jerdos-s"
            vb.memory = "1024"
            vb.cpus = 1
            end
        server.vm.provision "shell", inline: <<-SHELL
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --token $(cat ./config/token) -write-kubeconfig-mode=644
            sudo cp /usr/local/bin/kubectl /usr/bin/kubectl
        SHELL
    end

    #Second machine (agent)
    config.vm.define "jerdos-sSW" do |agent|
        agent.vm.box = "ubuntu/bionic64"
        agent.vm.hostname = "jerdos-sSW"
        agent.vm.network "private_network", ip: "192.168.56.111"
        agent.vm.provider "virtualbox" do |vb|
            vb.name = "jerdos-sW"
            vb.memory = "1024"
            vb.cpus = 1
            end
        agent.vm.provision "shell", inline: <<-SHELL
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            curl -sfL https://get.k3s.io |  K3S_URL=https://192.168.56.110:6443 sh -s - agent  --token $(cat ./config/token)
        SHELL
    end
end