VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    #First machine (server)
    config.vm.define "jerdos-sS" do |server|
        server.vm.box = "generic/debian10"
        server.vm.hostname = "jerdos-sS"
        server.vm.network "public_network", ip: "192.168.56.110"
        server.vm.provider "virtualbox" do |hv|
            hv.memory = "2048"
            hv.cpus = 2
            hv.name = "jerdos-sS"
        end
        server.vm.provision "shell", inline: <<-SHELL
            sudo mkdir -p /opt/config
            sudo chmod 777 /opt/config
        SHELL
        server.vm.provision "file", source: "./config", destination: "/opt/config"
        server.vm.provision "shell", inline: <<-SHELL
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --token $(cat /opt/config/token) --write-kubeconfig-mode 644
            sudo cp /usr/local/bin/kubectl /usr/bin/kubectl
        SHELL
    end

    #Second machine (agent)
    config.vm.define "jerdos-sSW" do |agent|
        agent.vm.box = "generic/debian10"
        agent.vm.hostname = "jerdos-sSW"
        agent.vm.network "public_network", ip: "192.168.56.111"
        agent.vm.provider "virtualbox" do |hv|
            hv.memory = "2048"
            hv.cpus = 2
            hv.name = "jerdos-sSW"
        end
        agent.vm.provision "shell", inline: <<-SHELL
            sudo mkdir -p /opt/config
            sudo chmod 777 /opt/config
        SHELL
        agent.vm.provision "file", source: "./config", destination: "/opt/config"
        agent.vm.provision "shell", inline: <<-SHELL
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            curl -sfL https://get.k3s.io |  K3S_URL=https://192.168.56.110:6443 sh -s - agent  --token $(cat /opt/config/token)
        SHELL
    end
end
