apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  description: "My Argo CD Project"
  sourceRepos:
    - "http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/*"
  destinations:
    - namespace: dev # On le cree
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

---


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: my-project # this app appartient au projet juste en haut
  source:
    repoURL: "http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/argocd-demo.git"
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
