apiVersion: v1
kind: Secret
metadata:
  name: gitlab-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  # match only the host & port—no path; must be quoted because of the colon and slashes
  url: "http://gitlab-webservice-default.gitlab.svc.cluster.local:8181"
  username: "root"
  password: "XOXO"
  # also needs to be quoted
  insecure: "true"
  forceHttpBasicAuth: "true"
