apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: app3
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app3-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: app3-content
          configMap:
            name: app3-index